version: "3"
services:
  db:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql

  web: &app
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - "TZ=Asia/Tokyo"
      # 環境変数でエディタにvimを指定
      - EDITOR=vim
    # dockerでbinding.pryを実行するための記述
    stdin_open: true
    tty: true

  webpacker:
    <<: *app
    depends_on: 
      - web
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
